dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [

    path('admin/', admin.site.urls),

    # 这里user的后面必须要加/，否则匹配不上
    re_path('^user/', include('dailyfreshuser.urls', namespace='dailyfreshuser')),
    re_path('^', include('dailyfreshgoods.urls', namespace='dailyfreshgoods')),
    re_path('^cart/', include('dailyfreshcart.urls', namespace='dailyfreshcart')),
    re_path('^order/', include('dailyfreshorder.urls', namespace='dailyfreshorder')),

    # 富文本编辑器
    re_path('^tinymce/', include('tinymce.urls')),

    #
    re_path('media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
]

dailyfresh/dailyfreshgoods/urls.py
from django.urls import path,re_path
from dailyfreshgoods import views

app_name = '[dailyfreshgoods]'
urlpatterns = [

    re_path('^(\d+)$', views.detail, name='detail'),
    re_path('^list(\d+)_(\d+)_(\d+)$', views.list, name='list'),
    re_path('^$', views.index, name='index'),
    re_path('^search', views.ordinary_search, name='ordinary_search'),


]

dailyfresh/dailyfreshuser/urls.py
from django.urls import path,re_path
from dailyfreshuser import views

app_name = '[dailyfreshuser]'
urlpatterns = [

    # 用户注册
    re_path('^register/$', views.register, name="register"),
    # register.html 进行ajax请求，查看用户名是否已经存在
    re_path('^register_exist', views.register_exist, name="register_exist"),
    # 接收注册提交过来的的信息
    re_path('^register_handle', views.register_handle, name="register_handle"),
    # 注册完成后跳转到登陆页面，注意：这里的login必须完全匹配（$），不然后面的login_handle无法匹配
    re_path('^login$', views.login, name="login"),
    # 处理登陆时提交过来的信息，若验证成功则跳转到用户信息info界面
    re_path('^login_handle', views.login_handle, name="login_handle"),
    # 用户信息界面
    re_path('^info', views.info, name="info"),
    # 订单模块
    re_path('^order/(\d+)', views.order, name="order"),
    # 收货地址
    re_path('^site', views.site, name="site"),
    # 用户登出
    re_path('^logout', views.logout, name="logout"),


]

dailyfresh/dailyfreshorder/models.py
from django.db import models


from dailyfreshgoods.models import GoodsInfo
from dailyfreshuser.models import UserInfo

# 总订单
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True, verbose_name="大订单号")
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, verbose_name="订单用户")
    odate = models.DateTimeField(auto_now=True, verbose_name="时间")
    oIsPay = models.BooleanField(default=False, verbose_name="是否支付")
    ototal = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="总价")
    oaddress = models.CharField(max_length=150, verbose_name="订单地址")
    # 虽然订单总价可以由多个商品的单价以及数量求得，但是由于用户订单的总价的大量使用，忽略total的冗余度

    class Meta:
        verbose_name = "订单"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.user.uname + "在" + str(self.odate) + "的订单"
        return "{0}在的订单{1}".format(self.user.uname, self.odate)

# 拆分订单
class OrderDetailInfo(models.Model):  # 大订单中的具体某一商品订单

    goods = models.ForeignKey(GoodsInfo, on_delete=models.CASCADE, verbose_name="商品")  # 关联商品信息
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE, verbose_name="订单")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="商品价格")
    count = models.IntegerField(verbose_name="商品数")

    class Meta:
        verbose_name = "订单详情"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.goods.gtitle + "(数量为" + str(self.count)  + ")"
        return "{0}(数量为{1})".format(self.goods.gtitle, self.count)

dailyfresh/dailyfreshuser/models.py
from django.db import models
from datetime import datetime
from dailyfreshgoods.models import GoodsInfo

class UserInfo(models.Model):
    """
    default,blank是python层面的约束，不影响数据库表的结构，若更改不需要重新迁移
    null=True是数据库表结构的更改，若修改则需要重新迁移
    """
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    ureceiveaddr = models.CharField(max_length=200 ,default='')
    uaddress = models.CharField(max_length=200 ,default='')
    upostcode = models.CharField(max_length=6 ,default='')
    uphone = models.CharField(max_length=11 ,default='')

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.uname

# 用户的浏览记录
class GoodsBrowser(models.Model):
    """
    用户的浏览记录，关联用户表和商品表
    """
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, verbose_name="用户ID")
    goods = models.ForeignKey(GoodsInfo, on_delete=models.CASCADE, verbose_name="商品ID")
    browser_time = models.DateTimeField(default=datetime.now, verbose_name="浏览时间")

    class Meta:
        verbose_name = "用户浏览记录"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "{0}浏览记录{1}".format(self.user.uname, self.goods.gtitle)

dailyfresh/dailyfreshuser/views.py
from django.shortcuts import render, redirect, reverse
from dailyfreshuser.models import *
from hashlib import sha1
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from . import user_decorator
from dailyfreshorder.models import *
from django.core.paginator import Paginator

# 首页
def index(request):
    return render(request, 'dailyfreshuser/index.html')

# 用户注册
def register(request):
    return render(request, 'dailyfreshuser/register.html')

# 接收用户注册的信息
def register_handle(request):
    # 接收用户输入的信息
    post = request.POST
    uname = post.get('user_name')
    upwd = post.get('pwd')
    upwd2 = post.get('cpwd')
    uemail = post.get('email')
    # 判断两次输入的密码
    if upwd != upwd2:
        return redirect('/user/register')
    # 对密码进行加密
    s1 = sha1()
    s1.update(upwd.encode('utf8')) # 指定编码格式，不然会报错
    upwd3 = s1.hexdigest()
    # 创建对象
    user = UserInfo()
    user.uname = uname
    user.upwd = upwd3
    user.uemail = uemail
    # 对象保存到数据库中
    user.save()
    # 注册成功，跳转到登陆的页面
    return redirect('/user/login')

# 判断用户名是否已经存在
def register_exist(request):
    # 前端js传入参数调用此方法，此时表单都没有提交，是GET方法
    user_name = request.GET['uname']
    count = UserInfo.objects.filter(uname=user_name).count()
    return JsonResponse({'count':count})

# 登陆界面
def login(request):
    uname = request.COOKIES.get('uname', '')
    context = {'title':'用户登录', 'error_name':0, 'error_pwd':0, 'uname':uname}
    return render(request, 'dailyfreshuser/login.html', context)

# 接收登陆的信息
def login_handle(request):
    # 接收请求信息
    post = request.POST
    uname = post.get('username')
    upwd = post.get('pwd')
    # 若记住密码没有被选中，则不会被提交，值为0
    jizhu = post.get('jizhu', 0)
    # 根据用户名来查询对象
    user = UserInfo.objects.filter(uname=uname) # filter若无结果，则为[],get则会报异常
    print(uname)
    #
    if len(user) == 1:
        s1 = sha1()
        s1.update(upwd.encode('utf8'))
        # 查出返回的是一个列表，返回一个或者多个
        if s1.hexdigest() == user[0].upwd:
            redict = HttpResponseRedirect('/user/info')
            # 记住用户名
            if jizhu != 0:
                redict.set_cookie('uname', uname)
            else:
                redict.set_cookie('uname', '', max_age=-1)
            # 记录session，跳转到用户界面时，可以直接拿到用户的信息
            request.session['user_id'] = user[0].id
            request.session['user_name'] = uname
            return redict
        else:
            context = {'title': '用户登陆', 'error_name': 0, 'error_pwd': 1, 'uname': uname, 'upwd': upwd}
            return render(request, 'dailyfreshuser/login.html', context)
    else:
        context = {'title': '用户登陆', 'error_name': 1, 'error_pwd': 0, 'uname': uname, 'upwd': upwd}
        return render(request, 'dailyfreshuser/login.html', context)

# 用户详情页，显示用户的邮箱以及姓名
@user_decorator.login
def info(request):
    username = request.session.get('user_name')
    user = UserInfo.objects.filter(uname=username).first()
    browser_goods = GoodsBrowser.objects.filter(user=user).order_by("-browser_time")
    goods_list = []
    if browser_goods:
        goods_list = [browser_good.good for browser_good in browser_goods]  # 从浏览商品记录中取出浏览商品
        explain = '最近浏览'
    else:
        explain = '无最近浏览'

    context = {
        'title': '用户中心',
        'page_name': 1,
        'user_phone': user.uphone,
        'user_address': user.uaddress,
        'user_name': username,
        'goods_list': goods_list,
        'explain': explain,
        'user_email':user.uemail,
    }
    return render(request, 'dailyfreshuser/user_center_info.html', context)

# 订单模块，显示用户的订单
@user_decorator.login
def order(request, index):
    user_id = request.session['user_id']
    orders_list = OrderInfo.objects.filter(user_id=int(user_id)).order_by('-odate')
    paginator = Paginator(orders_list, 2)
    page = paginator.page(int(index))
    context = {
        'paginator': paginator,
        'page': page,
        # 'orders_list':orders_list,
        'title': "用户中心",
        'page_name': 1,
    }
    return render(request, 'dailyfreshuser/user_center_order.html', context)


# 收货地址,根据记录的session查询
@user_decorator.login
def site(request):
    # 如果是用户登陆过来的，则直接查询用户的信息返回
    user = UserInfo.objects.get(id=request.session['user_id'])
    # 如果是用户修改收货地址POST过来的请求，则将更新后的收货地址返回
    if request.method == 'POST':
        user.ureceiveaddr = request.POST['ushou']
        user.uaddress = request.POST['uaddress']
        user.upostcode = request.POST['uyoubian']
        user.uphone = request.POST['uphone']
        user.save()
    context = {'title':'用户中心', 'user':user}
    return render(request, 'dailyfreshuser/user_center_site.html', context)

def logout(request):
    # 用户退出，清空所有的session
    request.session.flush()
    return redirect(reverse("dailyfreshuser:login")) # 注意：这里是双引号 302重定向到登陆界面
    #return redirect(reverse("dailyfreshgoods:index"))

dailyfresh/templates/dailyfreshuser/login.html
{% extends 'base_foot.html' %}
{% block head %}
<script>
	$(function () {
		name_error = false;
		pwd_error = false;

		if({{ error_name }} == 1){
		    //.为类选择器
		    $('.user_error').html('用户名错误').show()
		}

		if({{ error_pwd }} == 1){
		    $('.pwd_error').html('密码错误').show()
		}

		$('.name_input').blur(function () {
            if ($('.name_input').val().length == 0) {
                $('.user_error').html('请填写用户名').show()
                name_error = false;
            } else {
                $('.user_error').hide()
                name_error = true
            }
        });

		$('.pass_input').blur(function () {
			if ($('.pass_input').val().length == 0) {
			    $('.pwd_error').html('请输入密码').show()
				pwd_error = false;
			} else {
			    $('.pwd_error').hide()
				pwd_error=true;
			}
        });

    })
</script>
{% endblock head %}
{% block body %}
	<div class="login_top clearfix">
		<a href="{% url "dailyfreshgoods:index" %}" class="login_logo"><img src="/static/dailyfreshuser/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">立即注册</a>
				</div>
				<div class="form_input">
					<form action="/user/login_handle" method="post">
						<input type="text" name="username" class="name_input" value="{{uname}}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" value="{{upwd}}" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

dailyfresh/templates/dailyfreshuser/register.html
{% extends 'base_foot.html' %}
{% block head %}
	<script type="text/javascript" src="/static/dailyfreshuser/js/register.js"></script>
{% endblock head %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/dailyfreshuser/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/user/login">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/user/register_handle/">
					{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

dailyfresh/templates/dailyfreshuser/user_center_info.html
{% extends 'base.html' %}

{% block center_body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url "dailyfreshuser:info" %}" class="active">· 个人信息</a></li>
				<li><a href="{% url "dailyfreshuser:order" 1 %}">· 全部订单</a></li>
				<li><a href="{% url "dailyfreshuser:site" %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user_name}}</li>
							<li><span>联系方式：</span>{{user_phone}}</li>
							<li><span>电子邮箱：</span>{{ user_email }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">{{ explain }}</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				{% for good in goods_list %}
				<li>
					<a href="/{{ good.id }}"><img src="{{ MEDIA_URL }}{{ good.gpic }}"></a>
					<h4><a href="/{{good.id}}">{{ good.gtitle }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.gprice }}</span>
						<span class="unit">{{good.gprice }}/{{ good.gunit }}</span>
						<a href="/cart/add{{ good.id }}_1/" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>
		</div>
		</div>
	</div>

{% endblock center_body %}

dailyfresh/templates/dailyfreshuser/user_center_order.html
{% extends 'base.html' %}

{% block center_body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url "dailyfreshuser:info" %}">· 个人信息</a></li>
				<li><a href="{% url "dailyfreshuser:order" 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url "dailyfreshuser:site" %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{% for orderinfo in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ orderinfo.odate|date }}</li>
					<li class="col02">订单号：{{ orderinfo.oid }}</li>
					<li class="col02 stress">已支付</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
					<tr>
						<td width="55%">
							{% for order_detail in orderinfo.orderdetailinfo_set.all %}
							<ul class="order_goods_list clearfix">
								<li class="col01"><img src="{{ MEDIA_URL }}{{ order_detail.goods.gpic }}"></li>
								<li class="col02">{{ order_detail.goods.gtitle }}<em class="good_price">{{ order_detail.goods.gprice }}</em>元/<em>{{ order_detail.goods.gunit }}</em></li>
								<li class="col03">{{ order_detail.count }}件</li>
								<li class="col04"></li>
							</ul>
							{% endfor %}
						</td>
						<td width="15%">{{ orderinfo.ototal }}元</td>
						<td width="15%">已付款</td>
						<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
					</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
					{% if page.has_previous %}
					<a href="{% url "dailyfreshuser:order" page.previous_page_number %}">上一页</a>
					{% endif %}

					{% for index in paginator.page_range %}
					{% if index == page.number %}
					<a href="{% url "dailyfreshuser:order" index %}" class="active">{{ index }}</a>
					{% else %}
					<a href="{% url "dailyfreshuser:order" index %}">{{ index }}</a>
					{% endif %}
					{% endfor %}

					{% if page.has_next %}
					<a href="{% url "dailyfreshuser:order" page.next_page_number %}">下一页></a>
					{% endif %}
				</div>
		</div>
	</div>
	<script type="text/javascript">
		$(function () {
		    $('.col04').each(function () {
		        count = $(this).prev().text()
				price = $(this).prev().prev().find('.good_price').text()
                $(this).html(parseFloat(count,2)*parseFloat(price,2)+'元')
            })

        });
	</script>


{% endblock center_body %}

dailyfresh/templates/dailyfreshuser/user_center_site.html
{% extends 'base.html' %}

{% block center_body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="info">· 个人信息</a></li>
				<li><a href="order">· 全部订单</a></li>
				<li><a href="site" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>{{ user.uaddress }} ({{ user.ushou }} 收)  {{ user.uphone }}</dd>
					</dl>					
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="site" method="post">
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{user.ureceiveaddr}}">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="uaddress">{{ user.uaddress }}</textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="uyoubian" value="{{ user.upostcode }}">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="uphone" value="{{ user.uphone }}">
						</div>

						<input type="submit"  value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{% endblock center_body %}