dailyfresh/dailyfresh/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [

    path('admin/', admin.site.urls),

    # 这里user的后面必须要加/，否则匹配不上
    re_path('^user/', include('dailyfreshuser.urls', namespace='dailyfreshuser')),
    re_path('^', include('dailyfreshgoods.urls', namespace='dailyfreshgoods')),
    re_path('^cart/', include('dailyfreshcart.urls', namespace='dailyfreshcart')),
    re_path('^order/', include('dailyfreshorder.urls', namespace='dailyfreshorder')),

    # 富文本编辑器
    re_path('^tinymce/', include('tinymce.urls')),

    #
    re_path('media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
]

dailyfresh/dailyfreshgoods/urls.py
from django.urls import path,re_path
from dailyfreshgoods import views

app_name = '[dailyfreshgoods]'
urlpatterns = [

    re_path('^(\d+)$', views.detail, name='detail'),
    re_path('^list(\d+)_(\d+)_(\d+)$', views.list, name='list'),
    re_path('^$', views.index, name='index'),
    re_path('^search', views.ordinary_search, name='ordinary_search'),


]

dailyfresh/dailyfreshuser/urls.py
from django.urls import path,re_path
from dailyfreshuser import views

app_name = '[dailyfreshuser]'
urlpatterns = [

    # 用户注册
    re_path('^register/$', views.register, name="register"),
    # register.html 进行ajax请求，查看用户名是否已经存在
    re_path('^register_exist', views.register_exist, name="register_exist"),
    # 接收注册提交过来的的信息
    re_path('^register_handle', views.register_handle, name="register_handle"),
    # 注册完成后跳转到登陆页面，注意：这里的login必须完全匹配（$），不然后面的login_handle无法匹配
    re_path('^login$', views.login, name="login"),
    # 处理登陆时提交过来的信息，若验证成功则跳转到用户信息info界面
    re_path('^login_handle', views.login_handle, name="login_handle"),
    # 用户信息界面
    re_path('^info', views.info, name="info"),
    # 订单模块
    re_path('^order/(\d+)', views.order, name="order"),
    # 收货地址
    re_path('^site', views.site, name="site"),
    # 用户登出
    re_path('^logout', views.logout, name="logout"),


]

dailyfresh/dailyfreshgoods/models.py
from django.db import models
from tinymce.models import HTMLField

class TypeInfo(models.Model):
    ttitle = models.CharField(max_length=20)
    isDelete = models.BooleanField(default=False)
    def __str__(self):
        return self.ttitle


class GoodsInfo(models.Model):
    gtitle = models.CharField(max_length=20)
    gpic = models.ImageField(upload_to='dailyfreshgoods')
    gprice = models.DecimalField(max_digits=5, decimal_places=2)
    isDelete = models.BooleanField(default=False)
    gunit = models.CharField(max_length=20)
    gclick = models.IntegerField()
    gdescribe = models.CharField(max_length=500)
    gstock = models.IntegerField()
    gcontent = HTMLField()
    gtype = models.ForeignKey(TypeInfo, on_delete=models.CASCADE)

dailyfresh/dailyfreshgoods/views.py
from django.shortcuts import render
from .models import *
from django.core.paginator import Paginator
from dailyfreshcart.models import *

def index(request):
    # 查询各个分类的最新4条，最热4条数据
    typelist = TypeInfo.objects.all()
    #  _set 连表操作
    type0 = typelist[0].goodsinfo_set.order_by('-id')[0:4]  # 按照上传顺序
    type01 = typelist[0].goodsinfo_set.order_by('-gclick')[0:4]  # 按照点击量
    type1 = typelist[1].goodsinfo_set.order_by('-id')[0:4]
    type11 = typelist[1].goodsinfo_set.order_by('-gclick')[0:4]
    type2 = typelist[2].goodsinfo_set.order_by('-id')[0:4]
    type21 = typelist[2].goodsinfo_set.order_by('-gclick')[0:4]
    type3 = typelist[3].goodsinfo_set.order_by('-id')[0:4]
    type31 = typelist[3].goodsinfo_set.order_by('-gclick')[0:4]
    type4 = typelist[4].goodsinfo_set.order_by('-id')[0:4]
    type41 = typelist[4].goodsinfo_set.order_by('-gclick')[0:4]
    type5 = typelist[5].goodsinfo_set.order_by('-id')[0:4]
    type51 = typelist[5].goodsinfo_set.order_by('-gclick')[0:4]

    cart_num = 0
    # 判断是否存在登录状态
    # if request.session.has_key('user_id'):
    if 'user_id' in request.session:
        user_id = request.session['user_id']
        cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()

    context = {
        'title': '首页',
        'cart_num': cart_num,
        'guest_cart': 1,
        'type0': type0, 'type01': type01,
        'type1': type1, 'type11': type11,
        'type2': type2, 'type21': type21,
        'type3': type3, 'type31': type31,
        'type4': type4, 'type41': type41,
        'type5': type5, 'type51': type51,
    }

    return render(request, 'dailyfreshgoods/index.html', context)


def list(request, tid, pindex, sort):
    """

    :param request:
    :param tid:
    :param pindex:
    :param sort:
    :return:
    """
    typeinfo = TypeInfo.objects.get(pk=int(tid))
    news = typeinfo.goodsinfo_set.order_by('-id')[0:2]
    if sort == 1: # 默认
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-id')
    elif sort == 2: # 价格
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-gprice')
    elif sort == 3: #人气，点击量
        goods_list = GoodsInfo.objects.filter(gtype_id=int(tid)).order_by('-gclick')
    paginator = Paginator(goods_list, 4)
    page = paginator.page(int(pindex))
    context = {
        'title':typeinfo.ttitle,
        'guest_cart':1,
        'page':page,
        'typeinfo':typeinfo,
        'sort':sort,
        # 新品推荐
        'news':news
    }
    return render(request, 'dailyfreshgoods/list.html', context)


def detail(request, id):
    goods = GoodsInfo.objects.get(pk=int(id))
    goods.gclick = goods.gclick + 1
    goods.save()
    news = goods.gtype.goodsinfo_set.order_by('-id')[0:2]
    context = {
        'title':goods.gtype.ttitle,
        'guest_cart':1,
        'g':goods,
        'news':news,
        'id':id
    }
    return render(request, 'dailyfreshgoods/detail.html', context)


def ordinary_search(request):
    from django.db.models import Q

    search_keywords = request.GET.get('q', '')
    pindex = request.GET.get('page')
    search_status = 1
    cart_num, guest_cart = 0, 0

    try:
        user_id = request.session['user_id']
    except:
        user_id = None

    if user_id:
        guest_cart = 1
        cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()

    goods_list = GoodsInfo.objects.filter(
        Q(gtitle__icontains=search_keywords) |
        Q(gcontent__icontains=search_keywords) |
        Q(gdescribe__icontains=search_keywords)).order_by("gclick")

    if goods_list.count() == 0:
        # 商品的搜索结果为空，返回推荐的商品
        search_status = 0
        goods_list = GoodsInfo.objects.all().order_by("gclick")[:4]

    paginator = Paginator(goods_list, 3)
    page = paginator.page(int(pindex))

    context = {
        'title':'搜索列表',
        'search_status': search_status,
        'guest_cart': guest_cart,
        'cart_num': cart_num,
        'page': page,
        'paginator': paginator,
        'search_keywords':search_keywords,
    }

    return render(request, 'dailyfreshgoods/ordinary_search.html', context)

dailyfresh/templates/dailyfreshgoods/base.html
{% extends 'base.html' %}}
{% block center_body %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                <li><a href="/list1_1_1" class="fruit">新鲜水果</a></li>
                <li><a href="/list2_1_1" class="seafood">海鲜水产</a></li>
                <li><a href="/list3_1_1" class="meet">猪牛羊肉</a></li>
                <li><a href="/list4_1_1" class="egg">禽类蛋品</a></li>
                <li><a href="/list5_1_1" class="vegetables">新鲜蔬菜</a></li>
                <li><a href="/list6_1_1" class="ice">速冻食品</a></li>
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

<div class="breadcrumb">
    全部分类 > {{titile}}
   {% if id|default:' ' != ' ' %}
    > 商品详情
    {% endif %}
</div>
{% block center_content %}

{% endblock center_content %}

{% endblock center_body %}

dailyfresh/templates/dailyfreshgoods/detail.html
{% extends 'dailyfreshgoods/base.html' %}
{% block head %}
	<script type="text/javascript" src="/static/dailyfreshuser/js/jquery-1.12.4.min.js"></script>
	//通过绑定js事件实现随着商品数量的增长商品总价上涨
	<script type="text/javascript">
	function plus(){
		num = parseFloat($('.num_show').val())
		gstock = parseFloat($('.goods_stock').html())
		if (num<=gstock){
		    $('.num_show').val(num+1)
			$('.num_show').blur()
		}

	}

	function minus() {
	    num = parseFloat($('.num_show').val())
		if (num>1) {
			$('.num_show').val(num-1)
			$('.num_show').blur()
        }
        else {
			alert('商品的数量不可以小于1')
        }

    }

    $(function () {
        $('.num_show').blur(function () {
            num = parseInt($('.num_show').val())
			if (num<=1)
                num = 1
			gstock = parseInt($('.goods_stock').text())

			if (num>gstock)
				num = gstock

			// #id .class
			price = parseFloat($('#gprice').text())
			total = price * num

			$('.num_show').val(num)
			$('#gtotal').text(total.toFixed(2)+'元')

        });

    });

	</script>
{% endblock head %}
{% block center_content %}

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ MEDIA_URL }}{{ g.gpic }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{g.gtitle}}</h3>
			<p>{{g.gsubtitle}}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="gprice">{{g.gprice}}</em></span>
				<span class="show_unit">单  位：{{g.gunit}}</span>
				<span class="show_unit">库  存：<span class="goods_stock">{{ g.gstock }}</span></span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:plus();" class="add fr">+</a>
					<a href="javascript:minus();" class="minus fr">-</a>
				</div> 
			</div>
			<div class="total">总价：<em id="gtotal">{{g.gprice}}元</em></div>
			<div class="operate_btn">
				{% if request.session.user_name|default:'' != '' %}
				<a href="javascript:;" class="buy_btn">立即购买</a>
				{% else %}
				<a href="{% url "dailyfreshuser:login" %}" class="buy_btn">立即购买</a>
				{% endif %}
				{% if request.session.user_name|default:'' != '' %}
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
				{% else %}
				<a href="{% url "dailyfreshuser:login" %}" class="add_cart" id="add_cart">加入购物车</a>
				{% endif %}

			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for goods in news %}
					<li>
						<a href="/{{goods.id}}"><img src="{{ MEDIA_URL }}{{ goods.gpic }}"></a>
						<h4><a href="#">{{ goods.gtitle }}</a></h4>
						<div class="prize">￥{{ goods.gprice }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ g.gcontent|safe }}</dd>
				</dl>
			</div>

		</div>
	</div>


	<div class="add_jump"></div>

	<script type="text/javascript" src="/static/dailyfreshuser/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
        $(document).ready(function(){

            $(".buy_btn").click(function () {
                num = parseInt($('.num_show').val());
                $.get('/cart/add{{ g.id }}_'+num+'/',function (data) {
                    $('#show_count').text(data.count);
                });
                location.href = "/cart/";

            });

			$('#add_cart').click(function () {
				var $add_x = $('#add_cart').offset().top;
				var $add_y = $('#add_cart').offset().left;

				var $to_x = $('#show_count').offset().top;
				var $to_y = $('#show_count').offset().left;

				$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})

					//先判断是否登陆
					if ($('.login-btn').text().indexOf('登陆') >= 0){
						alert('请登陆后购买')
						location.href('/user/login')
						return;
					}
					//购物车添加动画
					$(".add_jump").stop().animate({
							'left': $to_y+7,
							'top': $to_x+7},
						"fast", function() {
							$(".add_jump").fadeOut('fast',function(){
								count = $('.num_show').val()
								$('#show_count').html(count);
						});

					});
                num = parseInt($('.num_show').val());
                $.get('/cart/add{{ g.id }}_'+num+'/',function (data) {
                    $('#show_count').text(data.count);
            	})

        });

    });

	</script>
{% endblock center_content %}

dailyfresh/templates/dailyfreshgoods/list.html
{% extends 'dailyfreshgoods/base.html'%}

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					{% for goods in news %}
					<li>
						<a href="{{ goods.id }}"><img src="{{ MEDIA_URL }}{{ goods.gpic }}"></a>
						<h4><a href="#">{{ goods.gtitle }}</a></h4>
						<div class="prize">￥{{ goods.gprice }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<!--注意视图函数中的传参顺序 另外在url中传递的链接全为字符型-->
				<a href="/list{{typeinfo.id}}_1_1"
				   {% if sort == "1" %}
				   class="active"
					{% endif %}
				>默认</a>
				<a href="/list{{typeinfo.id}}_1_2
				{% if sort == "2" %}
				class="active"
				{% endif %}
				">价格</a>
				<a href="/list{{typeinfo.id}}_1_3"
				{% if sort == "3" %}
				class="active"
				{% endif %}
				>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for g in page %}
				<li>
					<a href="/{{g.id}}"><img src="/static/{{g.gpic}}"></a>
					<h4><a href="/{{g.id}}">{{g.gtitle}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{g.gprice}}</span>
						<span class="unit">{{g.gunit}}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}

			</ul>

			<div class="pagenation">
				<!--判断是否为第一页-->
				{% if page.has_previous %}
					<a href="/list{{ typeinfo.id }}_{{ page.previous_page_num }}_{{ sort }}">上一页</a>
				{% endif %}

				{% for pindex in paginator.page_range %}
					{% if pindex == page.number %}
						<a href="/list{{ typeinfo.id }}_{{ page.previous_page_num }}_{{ sort }}" class="active">{{ pindex }}</a>
					{% else %}
						<a href="/list{{ typeinfo.id }}_{{ page.previous_page_num }}_{{ sort }}">{{ pindex }}</a>
					{% endif %}
				{% endfor %}

				<!--是否还有下页-->
				{% if page.has_next %}
					<a href="/list{{ typeinfo.id }}_{{ page.next_page_num }}_{{ sort }}">下一页</a>
				{% endif %}

			</div>
		</div>
	</div>

{% endblock center_content %}

dailyfresh/templates/dailyfreshgoods/ordinary_search.html
{% extends 'base.html' %}
{% block center_body %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                <li><a href="/list1_1_1/" class="fruit">新鲜水果</a></li>
                <li><a href="/list2_1_1/" class="seafood">海鲜水产</a></li>
                <li><a href="#" class="meet">猪牛羊肉</a></li>
                <li><a href="#" class="egg">禽类蛋品</a></li>
                <li><a href="#" class="vegetables">新鲜蔬菜</a></li>
                <li><a href="#" class="ice">速冻食品</a></li>
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="{% url "dailyfreshgoods:index" %}">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>
<script type="text/javascript">
    if({{ search_status }}==0){
        alert("您的查询结果为空，为您推荐以下商品");
    }
</script>
<div class="breadcrumb">
    全部分类
    {#        {{ title }}#}
    {#		{% if id|default:' ' != ' ' %}#}
    > 商品详情
    {#		{% endif %}#}
</div>

<div class="main_wrap clearfix">
    <ul class="goods_type_list clearfix">
        {%  for item in page %}
        <li>
            <a href="/{{ item.id }}/"><img src="{{ MEDIA_URL }}{{ item.gpic }}"></a>
            <h4><a href="/{{ item.id }}/">{{ item.gtitle }}</a></h4>
            <div class="operate">
                <span class="prize">￥{{ item.gprice }}</span>
                <span class="unit">{{ item.gunit }}</span>
                <a href="/cart/add{{ item.id }}_1/" class="add_goods" title="加入购物车"></a>
                <!--<a href="javasript:;/" class="add_goods" title="加入购物车"></a>-->
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="pagenation">
        {# 判断是否是第一页#}
        {% if page.has_previous %}
        <a href="{% url "dailyfreshgoods:ordinary_search" %}?q={{ search_keywords }}&amp;page={{ page.previous_page_number }}">上一页</a>
        {% endif %}

        {% for pindex in paginator.page_range %}
        {% if pindex == page.number %}
        <a href="#" class="active">{{ pindex }}</a>
        {% else %}
        <a href="{% url "dailyfreshgoods:ordinary_search" %}?q={{ search_keywords }}&amp;page={{ pindex }}">{{ pindex }}</a>
        {% endif %}
        {% endfor %}

        {#是否又第二页#}
        {% if page.has_next %}
        <a href="{% url "dailyfreshgoods:ordinary_search" %}?q={{ search_keywords }}&amp;page={{ page.next_page_number }}">下一页></a>
        {% endif %}
    </div>
</div>
{% endblock center_body %}