MyFirstDjango/MyFirstDjango/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from booktest import views

urlpatterns = [

    #简单字符匹配，若为空则调用
    path('', views.index),
    # 正则表达中添加括号，则表示将括号中的信息传递给request
    re_path('^(\d+)$', views.show),
    path('admin/', admin.site.urls),
    re_path('^booktest/', include('booktest.urls', namespace="booktest")),
    re_path('^tinymce/', include('tinymce.urls')),
    re_path(r'^search/', include('haystack.urls')),
]

MyFirstDjango/booktest/urls.py
from django.urls import path,re_path
from booktest import views

# 解决Django2中遇到在根目录下urls.py中的include方法的第二个参数namespace添加之后就出错的问题。请在[app_name]目录下的urls.py中的urlpatterns前面加上app_name='[app_name]'
app_name = '[booktest]'
urlpatterns = [

    # 正则表达中添加括号，则表示将括号中的信息传递给request
    #re_path('^getTest1/', views.getTest1),
    re_path('^postTest1/', views.postTest1),

    # 调用views中的postTest2函数，返回相应的参数和页面
    re_path('^postTest2/', views.postTest2),

    # 调用cookie
    re_path('^cookieTest/', views.cookieTest),

    # 重定向
    re_path('^redirectTest1/', views.redirectTest1),
    re_path('^redirectTest2/', views.redirectTest2),

    # session
    re_path('^session1/', views.session1),
    re_path('^session2/', views.session2),
    re_path('^session2_handle/', views.session2_handle),
    re_path('^session3/', views.session3),

    # 反向解析
    re_path('^(\d+)/(\d+)/', views.show1, name="show1"),

    #验证码
    re_path('^verifyCode', views.verifyCode),
    re_path('^verifyTest2', views.verifyTest2),
    re_path('^verifyTest1/', views.verifyTest1),

    #上传图片
    re_path('^uploadPic', views.uploadPic),
    re_path('^uploadHandle', views.uploadHandle),

    #省市选择
    re_path('^area$', views.area),
    re_path('^pro', views.pro),
    re_path('^city(\d+)', views.city),
    re_path('^dis(\d+)',views.dis),

    #富文本
    re_path('^htmlEditor$', views.htmlEditor),
    re_path('^htmlEditorHandle/', views.htmlEditorHandle),

    #缓存
    re_path('^cache1', views.cache1),

    #全文搜索
    re_path('^mysearch', views.mysearch),

    #
    re_path('^celeryTest', views.celeryTest),




]

MyFirstDjango/booktest/models.py
from django.db import models
from tinymce.models import HTMLField

class BookInfo(models.Model):
    btitle = models.CharField(max_length=20)
    bpub_date = models.DateTimeField()
    # 若添加下面代码，则数据库中的表名则会更改为制定的表名
    # class Meta():
    #     db_table = 'bookinfo'
    def __str__(self):
        return self.btitle


class HeroInfo(models.Model):
    hname = models.CharField(max_length=10)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=1000)
    '''
    在django2.0后，定义外键和一对一关系的时候需要加on_delete选项，此参数为了避免两个表里的数据不一致问题
    on_delete有CASCADE、PROTECT、SET_NULL、SET_DEFAULT、SET()五个可选择的值
    CASCADE：此值设置，是级联删除。
    PROTECT：此值设置，是会报完整性错误。
    SET_NULL：此值设置，会把外键设置为null，前提是允许为null。
    SET_DEFAULT：此值设置，会把设置为外键的默认值。
    SET()：此值设置，会调用外面的值，可以是一个函数。
    '''
    hbook = models.ForeignKey(BookInfo, on_delete=models.CASCADE)

    def __str__(self):
        return self.hname

class AreaInfo(models.Model):
    title = models.CharField(max_length=20)
    parea = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

class Test1(models.Model):
    content = HTMLField()

MyFirstDjango/booktest/views.py
from django.shortcuts import render,redirect
from booktest.models import *
from django.http import HttpResponse,HttpResponseRedirect,JsonResponse
#from django.template import RequestContext,loader
from django.conf import settings
import os
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from booktest.task import sayhello

def index(request):
    # temp = loader.get_template('booktest/index.html') # get_tenplate是去获取templates路径下（同级路径）的文件
    # return HttpResponse(temp.render()) #render方法是去解析html
    bookList = BookInfo.objects.all()
    context = {'list':bookList}
    return render(request, 'booktest/index.html', context)


def show(request, book_id):
    book = BookInfo.objects.get(pk=book_id)
    herolist = book.heroinfo_set.all()
    context = {'list':herolist}
    return render(request, 'booktest/show.html', context)

def postTest1(request):
    return render(request, 'booktest/postTest1.html')

#构造函数，由urls中的路由配置调用函数
def postTest2(request):
    # 获取postTest1页面提交过来的表单数据
    uname = request.POST['uname']
    upwd = request.POST['upwd']
    ugender = request.POST.get('ugender')
    uhobby = request.POST.getlist('uhobby')
    # 构造上下文
    context = {'uname':uname, 'upwd':upwd, 'ugender':ugender, 'uhobby':uhobby}
    return render(request, 'booktest/postTest2.html', context)


# Cookie练习
def cookieTest(request):
    response = HttpResponse()
    cookie = request.COOKIES
    if 't1' in cookie:
        response.write(cookie['t1'])
    #response.set_cookie('t1','abc')
    return response

# 重定向练习
def redirectTest1(request):
     #return HttpResponseRedirect('/booktest/redirectTest2')
    return redirect('/booktest/redirectTest2')

def redirectTest2(request):
    return HttpResponse('这是重定向来的页面')

# 通过用户登陆练习Session
def session1(request):
    uname = request.session.get('myname', '未登陆')
    context = {'uname':uname}
    return render(request, 'booktest/session1.html', context)

def session2(request):
    return render(request, 'booktest/session2.html')

def session2_handle(request):
    # 获取前端页面传入的用户名
    uname = request.POST['uname']
    # session（字典）中设置存储用户名
    request.session['myname'] = uname
    # 设置session的有效时间 0表示关闭浏览器的时候过期
    #request.session.set_expiry(0)
    # 登陆成功后，重定向到登陆的页面
    return redirect('/booktest/session1/')

def session3(request):
    # 删除session
    del request.session['myname']
    return redirect('/booktest/session1/')


def show1(request, id, id2):
    context = {"id":id}
    return render(request, 'booktest/show.html', context)


# 验证码练习
def verifyCode(request):
    #引入绘图模块
    from PIL import Image,ImageDraw,ImageFont
    #引入随机函数模块
    import random
    #定义变量，用于画面的背景色（RGB）、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(20, 100), 255)
    width = 100
    height = 25
    #创建画面
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    #构造字体对象
    font = ImageFont.truetype('Arial Bold.ttf', 23)
    #调用画笔的line()函数绘制干扰线
    for i in range(0, 50):
        begin = (random.randint(0, width), random.randint(0, height))
        end = (random.randint(0, width), random.randint(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        # 绘制线
        draw.line([begin, end], fill=fill)
    #调用画笔的point()函数绘制干扰点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        # 绘制点
        draw.point(xy, fill=fill)
    #定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    #随机选择4个值作为验证码
    rand_str = ''
    for i in range(4):
        temp_str = str1[random.randrange(0, len(str1))]
        rand_str += temp_str
        # 总宽度为100，每个字符从0，25...开始绘制
        draw.text((i*25,0),
                  temp_str,
                  (255, 255, 255),
                  font)
    #释放画笔
    del draw
    #session中记录验证码，与用户输入的进行对比
    request.session['code'] = rand_str
    #将图片保存到内存流中
    import io
    buf = io.BytesIO()
    im.save(buf, 'png')
    #将内存流中的内容输出到客户端
    return HttpResponse(buf.getvalue(), 'image/png')

def verifyTest1(request):
    return render(request, 'booktest/verifyTest1.html')

def verifyTest2(request):
    code1 = request.POST['code1']
    code2 = request.session['code']
    return HttpResponse('OK' if str(code1).lower() == str(code2).lower() else 'False')

#上传图片
def uploadPic(request):
    return render(request, 'booktest/uploadPic.html')

def uploadHandle(request):
    if request.method == "POST":
        f1 = request.FILES['pic1']
        #fname = '%sbooktest/%s' %(settings.MEDIA_ROOT, f1.name)
        fname = os.path.join(settings.MEDIA_ROOT, f1.name)
        with open(fname, 'wb') as pic:
            for c in f1.chunks():
                pic.write(c)
        return HttpResponse("上传成功，文件已经存储在" + '<img src="/static/media/%s"/>' %f1.name)
    else:
        return HttpResponse("Error")


#省市区选择
def area(request):
    return render(request, 'booktest/area.html')

def pro(request):
    proList = AreaInfo.objects.filter(parea__isnull=True) #.values()
    # # [{},{},{}]=====>{data:[]}
    # data1 = {'data':data}
    list = []
    # [[1,'北京'],[2,'天津'],...]
    for item in proList:
        list.append([item.id, item.title])#[1,'北京']
    # list--->[[],[],[]]
    return JsonResponse({'data':list})

def city(request, id):
    #parea_id=id 输入的省的id和数据库中某些数据的parea_id相等，不需要关联
    # parea__id=id 根据输入的id查找到parea，再找到parea_id和输入的id相同。
    cityList = AreaInfo.objects.filter(parea_id=id)
    list = []
    #[{id:1,title:北京},{id:2,title:天津},...]
    for item in cityList:
        list.append({'id':item.id,'title':item.title})
    return JsonResponse({'data':list})

def dis(request, id):
    #parea_id=id 输入的省的id和数据库中某些数据的parea_id相等，不需要关联
    # parea__id=id 根据输入的id查找到parea，再找到parea_id和输入的id相同，将parea_id与id关联
    disList = AreaInfo.objects.filter(parea_id=id)
    list = []
    #[{id:1,title:北京},{id:2,title:天津},...]
    for item in disList:
        list.append({'id':item.id,'title':item.title})
    return JsonResponse({'data':list})

#自定义编辑器
def htmlEditor(request):
    return render(request, 'booktest/htmlEditor.html')

def htmlEditorHandle(request):
    html = request.POST['hcontent']
    #改写更新这个模型类，先查询之前存储的信息
    test1 = Test1.objects.get(pk=1)
    test1.content = html
    test1.save()
    context = {'content':html}
    return render(request, 'booktest/htmlShow.html', context)

#添加视图缓存
@cache_page((60 * 15))
def cache1(request):
    #return HttpResponse('hello1')
    #return HttpResponse('hello2')
    cache.set('key1', 'value1', 600)
    return render(request, 'booktest/cache1.html')


#全文搜索+结巴分词
def mysearch(request):
    return render(request, 'booktest/mysearch.html')

#
def celeryTest(request):
    # print('hello ...')
    # import time
    # time.sleep(10)
    # print('world ...')
    #sayhello()
    sayhello.delay()

    return HttpResponse("hello world")

MyFirstDjango/templates/booktest/area.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="/static/booktest/js/jquery-1.12.4.min.js"></script>
    <script>
        //页面加载完成后执行下面的代码
        $(function () {


            //使用ajax加载省的信息
            pro = $('#pro')
            $.get('pro/', function (dic) {//{data:[1,'北京'],[2,'天津'],[]}
                //遍历一个数据，第二个参数是对每个元素应用的函数
                $.each(dic.data, function (index, item) {
                    pro.append('<option value="'+item[0]+'">'+item[1]+'</option>')
                })
            })

            //使用ajax加载市的信息
            $('#pro').change(function () {
                $.get('city'+$(this).val()+'/', function (list) {
                    city = $('#city')
                    city.empty().append('<option value="0">请选择市</option>')
                    $('#dis').empty().append('<option value="0">请选择区</option>')
                    //{data:[{id:1,title:北京},{id:2,title:天津},...]}
                    $.each(list.data, function (index, item) {
                        city.append('<option value="'+item.id+'">'+item.title+'</option>')
                    })
                    
                })
            })


            //使用ajax加载区的信息
            $('#city').change(function () {
                $.get('dis'+$(this).val()+'/', function (list) {
                    city = $('#dis')
                    city.empty().append('<option value="0">请选择区</option>')
                    //{data:[{id:1,title:北京},{id:2,title:天津},...]}
                    $.each(list.data, function (index, item) {
                        city.append('<option value="'+item.id+'">'+item.title+'</option>')
                    })

                })
            })



        });
    </script>
</head>
<body>
<select id="pro">
    <option value="0">请选择省</option>
</select>
<select id="city">
    <option value="0">请选择市</option>
</select>
<select id="dis">
    <option value="0">请选择区</option>
</select>
</body>
</html>

MyFirstDjango/templates/booktest/cache1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load cache %}
{% cache 500 hello %}
hello1
{% endcache %}
</body>
</html>

MyFirstDjango/templates/booktest/htmlEditor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript" src="/static/booktest/js/tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript">
        tinyMCE.init({
            'mode':'textareas',
            'theme':'advanced',
            'width':400,
            'height':100,
        });
    </script>
</head>
<body>
<form method="post" action="htmlEditorHandle/">
    {% csrf_token %}
    <input type="text" name="hname">
    <br>
    <textarea name="hcontent">哈哈，这是谁啊</textarea>
    <br>
    <input type="submit" value="提交">
</form>
</body>
</html>

MyFirstDjango/templates/booktest/htmlShow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{content|safe}}
</body>
</html>

MyFirstDjango/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tom</title>
</head>
<body>
<a href="{% url 'booktest:show1' '123' '456' %}">显示</a>
<ul>
    {%for book in list%}
    {% if forloop.counter|divisibleby:"2" %}
    <li style="color: red"><a href="{{book.id}}">{{forloop.counter}}:{{book.btitle}}</a></li>
    {% else %}
    <li style="color: blue"><a href="{{book.id}}">{{forloop.counter}}:{{book.btitle}}</a></li>
    {% endif %}
    {% empty %}
    <li>啥也没有找到</li>
    {%endfor%}
</ul>
</body>
</html>

MyFirstDjango/templates/booktest/mysearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/search/" target="_blank">
    <input type="text" name="q">
    <input type="submit" value="搜索">
</form>
</body>
</html>

MyFirstDjango/templates/booktest/postTest1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>请输入信息</title>
</head>
<body>
<form method="post" action="/booktest/postTest2/">
    用户名：<input type="text" name="uname"><br>
    密码：<input type="password" name="upwd"><br>
    性别：<input type="radio" name="ugender" value="男" checked="checked">男
         <input type="radio" name="ugender" value="女">女<br>
    爱好：<input type="checkbox" name="uhobby" value="跑步">跑步
         <input type="checkbox" name="uhobby" value="音乐">音乐
         <input type="checkbox" name="uhobby" value="羽毛球">羽毛球<br>
    <input type="submit" value="提交">
</form>
</body>
</html>

MyFirstDjango/templates/booktest/postTest2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
姓名：{{uname}}<br>
密码：{{upwd}}<br>
性别：{{ugender}}<br>
<!--爱好：{{uhobby}}<br>-->
爱好：{% for hobby in uhobby %}
{{hobby}}
{% endfor %}
</body>
</html>

MyFirstDjango/templates/booktest/session1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
你好：{{ uname }}
<br>
<a href="/booktest/session2">登陆</a>
<br>
<a href="/booktest/session3/">退出</a>
</body>
</html>

MyFirstDjango/templates/booktest/session2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="/booktest/session2_handle/">
    <input type="text" name="uname">
    <input type="submit" name="登陆">
</form>
</body>
</html>

MyFirstDjango/templates/booktest/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% comment %}
    {%for hero in list%}
    <li>{{hero.hname}}</li>
    {%endfor%}
    {% endcomment %}
    {{id}}
</ul>
</body>
</html>

MyFirstDjango/templates/booktest/uploadPic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传图片</title>
</head>
<body>
<form action="uploadHandle" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="pic1">
    <br>
    <input type="submit" value="上传">
</form>
</body>
</html>

MyFirstDjango/templates/booktest/verifyTest1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load static from staticfiles %}
<!--<script type="text/javascript" src="/static/booktest/js/jquery-1.12.4.min.js"></script>-->
<script type="text/javascript" src="{% static 'booktest/js/jquery-1.12.4.min.js' %}"></script>
<form action="/booktest/verifyTest2" method="post">
    <input type="text" name="code1">
    <br>
    <img id='verifycode' src="/booktest/verifyCode"/>
    <span id='verifycodeChange'>看不清，换一个</span>
    <br>
    <input type="submit" value="提交">
</form>
<script type="text/javascript">
    $(function(){
        $('#verifycodeChange').css('cursor','pointer').click(function() {
            $('#verifycode').attr('src',$('#verifycode').attr('src')+1)
        });
    });
</script>
</body>
</html>